name: Build and release syrius

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    environment: wallet-connect
    env:
        WALLET_CONNECT_PROJECT_ID: ${{ secrets.WC_PROJECT_ID }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          flutter-version: "3.10.2"
      - name: Check flutter version
        run: flutter --version
      - name: Build syrius desktop
        run: |
          flutter config --enable-windows-desktop
          flutter build -v windows --dart-define=WC_PROJECT_ID=$env:WALLET_CONNECT_PROJECT_ID --release   